apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jaorr95/test-argo-tools.git
    targetRevision: HEAD
    path: projects/argo-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true